# 시설 유형별로 가장 긴 샘플들 병합

In [1]:
import pandas as pd 
import numpy as np
import pickle
from sklearn.preprocessing import MinMaxScaler
import joblib

## 적용할 파일 경로 load

In [2]:
def file_merge(address):
    new=pd.DataFrame()
    for file in address:
        data=pd.read_csv(file)
        new=pd.concat([new,data])

    new.to_csv("../Merged_Data/By_Length.csv",index=False)
    
    return new

In [3]:
address=['../Grouped_Data/air_indoor_도서관/Mapped/ICW0W2000094.csv',
        '../Grouped_Data/air_indoor_초등학교/Mapped/ICW0W2000022.csv',
        '../Grouped_Data/air_indoor_체육시설/Mapped/ICW0W2001037.csv',
        '../Grouped_Data/air_indoor_중학교/Mapped/ICW0W2000020.csv']

merged_data=file_merge(address)

## scaler 훈련&저장 , scaler 적용된 파일을 별도의 경로에 저장

In [4]:
def train_scaler(new,columm_list):
    file=pd.DataFrame()
    file["time"]=new["time"]
    for columm in columm_list:
        scaler=MinMaxScaler().fit(np.array(new[columm]).reshape(-1,1))
        joblib.dump(scaler,"../Merged_Data/Scaler/{:s}.pkl".format(columm))
        file[columm]=scaler.transform(np.array(new[columm]).reshape(-1,1))
    file.to_csv("../Merged_Data/{:s}.csv".format('Scaled'),index=False)
    
    return file

In [5]:
columm_list=[]
columm_list=merged_data.columns
columm_list=columm_list.drop("time")

train_scaler(merged_data,columm_list)

,time,in_co2,in_humi,in_pm10,in_temp,in_voc,Y_pm10
0,2020-06-01 00:00:00+00:00,0.389964,0.473001,0.240888,0.719710,0.004820,0.200603
1,2020-06-01 01:00:00+00:00,0.385841,0.486241,0.200603,0.713185,0.007584,0.171401
2,2020-06-01 02:00:00+00:00,0.382704,0.497501,0.171401,0.705381,0.004179,0.155385
3,2020-06-01 03:00:00+00:00,0.379933,0.507269,0.155385,0.698556,0.003278,0.143053
4,2020-06-01 04:00:00+00:00,0.379093,0.518951,0.143053,0.694177,0.010778,0.123596
...,...,...,...,...,...,...,...
6618,2023-01-31 18:00:00+00:00,0.117454,0.345535,0.185530,0.188019,0.025577,0.169087
6619,2023-01-31 19:00:00+00:00,0.109944,0.349948,0.169087,0.187493,0.026248,0.158674
6620,2023-01-31 20:00:00+00:00,0.101463,0.355140,0.158674,0.188676,0.027310,0.152645
6621,2023-01-31 21:00:00+00:00,0.090513,0.354361,0.152645,0.186617,0.026228,0.154563
6622,2023-01-31 22:00:00+00:00,0.083712,0.358515,0.154563,0.186223,0.027069,0.158126